// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCR0Iuc9UdUz-zvZ_SbO0TQoR48ffI6tE',
    appId: '1:324113708961:web:879f3d001de8722f36bde0',
    messagingSenderId: '324113708961',
    projectId: 'cine-world-9ab61',
    authDomain: 'cine-world-9ab61.firebaseapp.com',
    storageBucket: 'cine-world-9ab61.appspot.com',
    measurementId: 'G-54Z2W0S7NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0veg8g9xBYvxgPKiLAkAARrPeDnjRrdk',
    appId: '1:324113708961:android:9557d50993fc4c6636bde0',
    messagingSenderId: '324113708961',
    projectId: 'cine-world-9ab61',
    storageBucket: 'cine-world-9ab61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhVyHTeLlXypCvi8MsQrk92txZ8_0eVWg',
    appId: '1:324113708961:ios:8b06d0f40e68805736bde0',
    messagingSenderId: '324113708961',
    projectId: 'cine-world-9ab61',
    storageBucket: 'cine-world-9ab61.appspot.com',
    iosBundleId: 'com.example.weMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhVyHTeLlXypCvi8MsQrk92txZ8_0eVWg',
    appId: '1:324113708961:ios:9c2a854b3a797aa136bde0',
    messagingSenderId: '324113708961',
    projectId: 'cine-world-9ab61',
    storageBucket: 'cine-world-9ab61.appspot.com',
    iosBundleId: 'com.example.weMovies.RunnerTests',
  );
}
